name:                haskell-gce
version:             0.1.0.0
github:              "rebeccaskinner/haskell-gce"
license:             Apache-2.0
author:              "Rebecca Skinner"
maintainer:          "rebecca@rebeccaskinner.net"
copyright:           "2019 Rebeccak Skinner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rebeccaskinner/haskell-gce#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10 && < 0.11
- text >= 1.2 && < 1.3
- transformers >= 0.5 && < 0.6
- mtl >= 2.2 && < 2.3
- http-client >= 0.5 && < 0.6
- http-client-tls >= 0.3 && < 0.4
- aeson >= 1.4 && < 1.5
- containers >= 0.6 && < 0.7
- lens >= 4.17 && < 4.18
- scientific >= 0.3 && < 0.4
- hoauth2 >= 1.8 && < 1.9
- jwt >= 0.9 && < 0.10
- cryptonite >= 0.25 && < 0.26
- jwt >= 0.9 && < 0.10
- time >= 1.8 && < 1.9
- http-types >= 0.12 && < 0.13

library:
  source-dirs: src
  default-extensions:
    - GADTs
    - OverloadedStrings
    - LambdaCase
    - RankNTypes
    - FlexibleContexts
    - FlexibleInstances
    - ScopedTypeVariables
    - TypeApplications
    - TypeFamilies
    - BangPatterns
    - ExistentialQuantification
    - FunctionalDependencies
    - MultiParamTypeClasses
    - DeriveFunctor
    - GeneralizedNewtypeDeriving

executables:
  haskell-gce-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-gce
    default-extensions:
    - GADTs
    - OverloadedStrings
    - LambdaCase
    - RankNTypes
    - FlexibleContexts
    - FlexibleInstances
    - ScopedTypeVariables
    - TypeApplications
    - TypeFamilies
    - BangPatterns
    - ExistentialQuantification
    - FunctionalDependencies
    - MultiParamTypeClasses
    - DeriveFunctor
    - GeneralizedNewtypeDeriving

tests:
  haskell-gce-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-gce
    default-extensions:
    - GADTs
    - OverloadedStrings
    - LambdaCase
    - RankNTypes
    - FlexibleContexts
    - FlexibleInstances
    - ScopedTypeVariables
    - TypeApplications
    - TypeFamilies
    - BangPatterns
    - ExistentialQuantification
    - FunctionalDependencies
    - MultiParamTypeClasses
    - DeriveFunctor
    - GeneralizedNewtypeDeriving
